import { defineArrayMember, defineField, defineType } from "sanity";

export const bookingContent = defineType({
  name: "bookingContent",
  title: "Buchung",
  type: "document",
  groups: [
    { name: "intro", title: "Einleitung", default: true },
    { name: "provider", title: "Buchungsanbieter" },
    { name: "fallback", title: "Fallback" },
  ],
  fields: [
    defineField({
      name: "eyebrow",
      title: "Label",
      type: "string",
      group: "intro",
      initialValue: "Termin buchen",
    }),
    defineField({
      name: "title",
      title: "Titel",
      type: "string",
      group: "intro",
      initialValue: "Gartenarbeit direkt planen.",
    }),
    defineField({
      name: "intro",
      title: "Einleitung",
      type: "text",
      rows: 4,
      group: "intro",
    }),
    defineField({
      name: "providerName",
      title: "Name des Anbieters",
      type: "string",
      group: "provider",
      initialValue: "Online-Buchung",
    }),
    defineField({
      name: "providerUrl",
      title: "Buchungslink",
      type: "url",
      group: "provider",
      description: "Direkter Link zum Drittanbieter, z. B. Calendly, Cal.com oder ein anderer Buchungsdienst.",
      validation: (rule) => rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "embedUrl",
      title: "Embed-URL",
      type: "url",
      group: "provider",
      description: "Optional: URL, die in einem iframe eingebettet werden darf.",
      validation: (rule) => rule.uri({ scheme: ["http", "https"] }),
    }),
    defineField({
      name: "fallbackTitle",
      title: "Fallback – Titel",
      type: "string",
      group: "fallback",
      initialValue: "Online-Buchung folgt",
    }),
    defineField({
      name: "fallbackBody",
      title: "Fallback – Text",
      type: "text",
      rows: 3,
      group: "fallback",
    }),
    defineField({
      name: "primaryCtaLabel",
      title: "Button 1 – Text",
      type: "string",
      group: "fallback",
      initialValue: "Kontakt aufnehmen",
    }),
    defineField({
      name: "primaryCtaHref",
      title: "Button 1 – Link",
      type: "string",
      group: "fallback",
      initialValue: "/kontakt",
    }),
    defineField({
      name: "secondaryCtaLabel",
      title: "Button 2 – Text",
      type: "string",
      group: "fallback",
      initialValue: "Anrufen",
    }),
    defineField({
      name: "secondaryCtaHref",
      title: "Button 2 – Link",
      type: "string",
      group: "fallback",
    }),
    defineField({
      name: "notes",
      title: "Hinweise",
      type: "array",
      group: "fallback",
      of: [defineArrayMember({ type: "string" })],
    }),
  ],
  preview: { prepare: () => ({ title: "Buchung" }) },
});
